name = "landing-lagoon"
main = "dist/_worker.js/index.js" 
compatibility_date = "2025-10-30"

[assets]
binding = "ASSETS"
directory = "./dist"

[[d1_databases]]
binding = "DB" # <-- This is the variable name you will use in Astro: locals.runtime.env.DB
database_name = "clients_db"
database_id = "ad962df1-c7a0-4bb0-928d-466d8b4c0737"